
workdir: experiments/GaussianSLAM
run_name: vlm_abl_reg5e-6-rerun-r3

# planning parameters
policy: 
  name: astar_greedy
  planning_queue_size: 30

bev_number_size: 1.0
bev_number_thickness: 2
H_reg_lambda: 0.000001
num_frames: &total_frames 2000
checkpoint_interval: 1000
# number of keyframes for local mapping
forward_step_size: 0.05
turn_angle: 5.
path_end_weight: 60.
opacity_pixel_weight: 0.0001

report_global_progress_every: 10
report_iter_progress: true

save_checkpoints: true
scene_radius_depth_ratio: 3
use_wandb: false
img_height: 800
img_width: 800
downsample_pcd: 4

SLAM:
  Dataset:
    pcd_downsample: 64

  Training:
    kf_min_translation: 0.01
    single_thread: False
    window_size: 20
    pose_window: 10

# Exploration parameters:
explore:
  use_frontier: true 
  height_range: 0.6
  prune_invisible: false
  sample_view_num: 256
  sample_range: 1.
  min_range: 0.5
  cell_size: 0.05
  centering: True
  shortcut_path: True
  add_random_gaussians: True
  frontier_select_method: "vlm"